all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/keys/proxmox-tg-cts
    trafficgrid_control_plane_ip: "10.20.20.200"
    trafficgrid_backend_url: "http://{{ trafficgrid_control_plane_ip }}:18420"

  children:
    workers:
      hosts:
        tg-worker-01:
          ansible_host: 10.10.10.106
        tg-worker-02:
          ansible_host: 10.10.10.107
        tg-worker-03:
          ansible_host: 10.10.10.108
        tg-worker-04:
          ansible_host: 10.10.10.109
